const MODS={"1": "Centrale operativa e trasmissioni", "2": "Tecniche operative e controllo del territorio", "3": "Patenti di guida", "4": "Diritto penale e penale militare", "5": "SDI", "6": "Diritto costituzionale", "7": "Diritto di polizia", "8": "Procedura penale e tecniche investigative", "9": "Esame testimoniale", "10": "Tutela dei soggetti vulnerabili", "11": "Tecnica professionale", "12": "Informatica d’Arma", "13": "Storia dell’Arma", "14": "Comunicazione interpersonale", "15": "Tecniche di apprendimento"};
const COURSES={CC:{name:'Quiz Carabinieri',desc:'Banca di allenamento · 15 materie',mods:[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]}};
const selectedCourse=()=>'CC';
const profileKey=(part)=>`quiz-carabinieri:${selectedCourse()||'unselected'}:${part}`;
let SETTINGS={timer:75,length:20,passMark:75};
const S={catalog:null,studyModule:null,questions:[],tab:'home',favorites:new Set(),favoriteBank:{},mistakes:new Set(),mistakeBank:{},stats:{},session:null,showCourseSelector:false};
function loadCourseState(){let raw={};try{raw=JSON.parse(localStorage.getItem(profileKey('settings'))||'{}')}catch{} SETTINGS=Object.assign({timer:75,length:20,passMark:75},raw);try{S.favorites=new Set(JSON.parse(localStorage.getItem(profileKey('favorites'))||'[]'))}catch{S.favorites=new Set()}try{S.favoriteBank=JSON.parse(localStorage.getItem(profileKey('favoriteBank'))||'{}')||{}}catch{S.favoriteBank={}}try{S.mistakes=new Set(JSON.parse(localStorage.getItem(profileKey('mistakes'))||'[]'))}catch{S.mistakes=new Set()}try{S.mistakeBank=JSON.parse(localStorage.getItem(profileKey('mistakeBank'))||'{}')||{}}catch{S.mistakeBank={}}try{S.stats=JSON.parse(localStorage.getItem(profileKey('stats'))||'{}')||{}}catch{S.stats={}}}
loadCourseState();
const course=()=>COURSES[selectedCourse()]||COURSES.CC;
const activeMods=()=>course().mods;
const activeQuestions=()=>S.questions.filter(q=>activeMods().map(String).includes(String(q.module)));

const conceptKey=q=>q.conceptId||`${q.module}|${q.chapter||''}|${q.subtopic||''}|${q.question}`;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(profileKey('settings'),JSON.stringify(SETTINGS));localStorage.setItem(profileKey('favorites'),JSON.stringify([...S.favorites]));localStorage.setItem(profileKey('favoriteBank'),JSON.stringify(S.favoriteBank));localStorage.setItem(profileKey('mistakes'),JSON.stringify([...S.mistakes]));localStorage.setItem(profileKey('mistakeBank'),JSON.stringify(S.mistakeBank));localStorage.setItem(profileKey('stats'),JSON.stringify(S.stats))}
function normalize(q){let answers=Array.isArray(q.answers)&&q.answers.length?q.answers:(Array.isArray(q.answersIt)?q.answersIt:[]);return {...q,id:String(q.id||''),question:String(q.question||q.questionIt||''),answers:answers.map(String).slice(0,4),correct:Number(q.correct),explanation:String(q.explanation||q.explanationIt||'')}}
function validQuestion(q){return !!q&&q.id&&q.question&&Array.isArray(q.answers)&&q.answers.length>=3&&Number.isInteger(q.correct)&&q.correct>=0&&q.correct<q.answers.length&&q.module!=null}
function shuffle(a){let x=[...a];for(let i=x.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function uniqueConcepts(items){let seen=new Set();return items.filter(q=>{let k=conceptKey(q);if(seen.has(k))return false;seen.add(k);return true})}
function unseenPool(n=20){return shuffle(uniqueConcepts(activeQuestions().filter(q=>!(S.stats[q.id]?.attempts>0)))).slice(0,n)}
function weakPool(n=20){let pool=uniqueConcepts(activeQuestions().filter(q=>S.stats[q.id]?.attempts>0));pool.sort((a,b)=>{let A=S.stats[a.id],B=S.stats[b.id],sa=(A.correct||0)/(A.attempts||1),sb=(B.correct||0)/(B.attempts||1);return sa-sb||(A.lastSeen||0)-(B.lastSeen||0)});return pool.slice(0,n)}
function adaptivePool(n=20){let now=Date.now(),pool=uniqueConcepts(activeQuestions());pool.sort((a,b)=>score(b,now)-score(a,now));return pool.slice(0,n)}
function score(q,now){let x=S.stats[q.id];if(!x)return 1000+Math.random()*20;let acc=(x.correct||0)/(x.attempts||1),age=Math.min(30,(now-(x.lastSeen||0))/86400000);return (1-acc)*500+age*8+Math.max(0,3-(x.attempts||0))*35+(q.difficulty||1)*5}
function go(tab){if(S.session?.timer)clearInterval(S.session.timer);S.tab=tab;S.session=null;render();window.scrollTo(0,0)}
function setTabs(){document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===S.tab));}
function card(icon,title,sub,action){return `<div class="card" data-action="${action}"><div class="ico">${icon}</div><div class="grow"><strong>${title}</strong><small>${sub}</small></div><b>›</b></div>`}
function studyIntelligence(){let aq=activeQuestions(),now=Date.now(),seen=aq.filter(q=>(S.stats[q.id]?.attempts||0)>0).length,coverage=aq.length?Math.round(seen/aq.length*100):0,due=spacedDuePool(999).length,weak=weakPool(999).filter(q=>((S.stats[q.id]?.correct||0)/(S.stats[q.id]?.attempts||1))<.75).length;let mods=activeMods().map(n=>({n,...moduleMetrics(n)})).filter(x=>x.attempts>0).sort((a,b)=>a.accuracy-b.accuracy||a.coverage-b.coverage),focus=mods[0];return `<section class="studyIntel"><div class="studyIntelHead"><div><small>STUDIO INTELLIGENTE</small><h2>La mia preparazione</h2></div><b>${coverage}%</b></div><div class="progress intelProgress"><i data-progress="${coverage}"></i></div><div class="intelGrid"><div><b>${seen}/${aq.length}</b><span>Domande viste</span></div><div><b>${due}</b><span>Da ripassare</span></div><div><b>${weak}</b><span>Deboli</span></div></div>${focus?`<div class="focusLine"><span>Priorità: <b>${String(focus.n).endsWith('L')?focus.n:'Materia '+focus.n} ${esc(MODS[focus.n]||'')}</b></span><span>${focus.accuracy}%</span></div>`:''}<button class="continueStudy" data-action="continueStudy">▶ Continua studio intelligente</button><small class="intelHint">Prima ripassi in scadenza, poi domande mai viste e aree deboli.</small></section>`}
function home(){let t=totals(),p=t.a?Math.round(t.c/t.a*100):0;return `<h1>Quiz Carabinieri</h1><div class="hero"><img src="assets/carabiniere-hero-v3.png?v=3.2.0" alt="Illustrazione di una carabiniera in uniforme"><div class="heroText"><b>Il tuo prossimo traguardo.</b><small>15 materie · ${activeQuestions().length} domande · Studio intelligente</small></div></div>${studyIntelligence()}<div class="stats3 homeStats"><div class="statCard"><b>${p}%</b><small>Precisione</small></div><div class="statCard"><b>${reviewItems().length}</b><small>Errori</small></div><div class="statCard"><b>${S.favorites.size}</b><small>Preferiti</small></div></div>${card('▣','Studia per materia','Materie, capitoli e dispense allegate','go-study')}${card('⚡','Quiz rapido',`${Math.min(SETTINGS.length,activeQuestions().length)} domande con spiegazione`,'startQuiz')}${card('◎','Ripasso intelligente','Errori, domande mai viste e aree deboli','startAdaptive')}${card('◷','Simulazione configurabile','Parametri di allenamento personalizzabili','examSetup')}${card('⚙','Impostazioni','Timer, lunghezza quiz e soglia','settingsScreen')}${installCard()}<div class="disclaimer">Banca di allenamento dalle dispense caricate, con approfondimenti ufficiali online per Centrale operativa. Non è una banca ufficiale d’esame. Banca ampliata: 17 dispense e 3 fonti ufficiali online; copertura parziale. Le risposte seguono i materiali di studio; le parti ambigue non sono incluse.</div>`}

let deferredInstallPrompt=null;
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
function installCard(){if(isStandalone())return `<div class="installReady"><b>✓ Quiz Carabinieri installata</b><small>Stai usando la versione app.</small></div>`;return `<div class="installCta"><div class="installCtaIcon">↓</div><div class="grow"><b>Installa Quiz Carabinieri</b><small>${isIOS()?'Aggiungila alla schermata Home':'Usala come una vera app sul dispositivo'}</small></div><button class="installBtn" data-action="installApp">Installa</button></div><div id="iosInstallHelp" class="iosInstallHelp hidden"><b>Installa su iPhone / iPad</b><span>1. Tocca Condividi ⎋ nel browser</span><span>2. Seleziona “Aggiungi alla schermata Home”</span><span>3. Attiva “Apri come app web” e tocca Aggiungi</span><button class="installHelpClose" data-action="closeInstallHelp">Chiudi</button></div>`}
async function installApp(){if(isStandalone())return;if(deferredInstallPrompt){let p=deferredInstallPrompt;deferredInstallPrompt=null;await p.prompt();try{await p.userChoice}catch{}render();return}if(isIOS()){document.querySelector('#iosInstallHelp')?.classList.remove('hidden');return}alert('Apri il menu del browser e scegli “Installa app” o “Aggiungi alla schermata Home”.')}
function closeInstallHelp(){document.querySelector('#iosInstallHelp')?.classList.add('hidden')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;if(S.tab==='home'&&!S.session&&selectedCourse())render()});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;if(S.tab==='home'&&!S.session)render()});

function statModule(id,x){if(x&&x.module!=null)return String(x.module);let q=S.questions.find(q=>q.id===id);if(q)return String(q.module);let m=String(id).match(/^DYN-([^-]+)-/);return m?String(m[1]):''}
function moduleMetrics(n){let qs=activeQuestions().filter(q=>String(q.module)===String(n)),bankConcepts=new Set(qs.map(q=>conceptKey(q))),attempts=0,correct=0,wrong=0,seen=new Set();Object.entries(S.stats).forEach(([id,x])=>{if(statModule(id,x)!==String(n))return;attempts+=x.attempts||0;correct+=x.correct||0;wrong+=x.wrong||0;let k=x.conceptKey||id;if((x.attempts||0)>0&&bankConcepts.has(k))seen.add(k)});let accuracy=attempts?Math.round(correct/attempts*100):0;let target=Math.max(1,bankConcepts.size);let coverage=Math.min(100,Math.round(seen.size/target*100));return {bank:qs.length,target,attempts,correct,wrong,seen:seen.size,accuracy,coverage}}
function study(){if(S.studyModule!=null)return subjectView(S.studyModule);return `<h1>Materie e capitoli</h1><div class="selectorIntro">${S.catalog.subjectCount} materie · ${activeQuestions().length} domande · ${S.catalog.chapterCount} capitoli didattici. Banca di allenamento con copertura parziale.</div><input class="bankSearch" data-filter="bank" type="search" placeholder="Cerca una materia…" aria-label="Cerca una materia">${activeMods().map(n=>{let m=moduleMetrics(n),subject=S.catalog.subjects.find(x=>x.module==n);return `<button class="module bankItem" data-search="${esc(MODS[n].toLocaleLowerCase('it'))}" data-action="subjectScreen" data-module="${n}"><div class="m">${n}</div><div class="grow"><b>${esc(MODS[n])}</b><div class="muted">${m.bank} domande · ${subject.chapterCount} capitoli</div><div class="progress"><i data-progress="${m.coverage}"></i></div><small>${m.attempts} risposte · ${m.wrong} errori</small></div><b>›</b></button>`}).join('')}`}
function quick(){return `<h1>Quiz • ${course().name}</h1>${card('⚡','Quiz rapido',`${SETTINGS.length} domande con spiegazione immediata`,'startQuiz')}${card('◆','Domande di approfondimento','Livello di difficoltà 3','startDifficult')}${card('◷','Simulazione di allenamento',`${SETTINGS.timer}s per domanda • soglia di allenamento ${SETTINGS.passMark}%`,'examSetup')}`}
function totals(){let a=0,c=0,w=0;Object.values(S.stats).forEach(x=>{a+=x.attempts||0;c+=x.correct||0;w+=x.wrong||0});return {a,c,w}}
function stats(){let t=totals(),p=t.a?Math.round(t.c/t.a*100):0;return `<h1>Progressi</h1><div class="score"><div class="pct">${p}%</div><div class="muted">Precisione complessiva</div></div><div class="stats3"><div class="statCard"><b>${t.a}</b><small>Risposte</small></div><div class="statCard"><b>${t.c}</b><small>Corrette</small></div><div class="statCard"><b>${t.w}</b><small>Errori</small></div></div>${activeMods().map(n=>{let m=moduleMetrics(n);return `<div class="module"><div class="m">${String(n).endsWith('L')?n:'M'+n}</div><div class="grow"><b>${MODS[n]}</b><div class="progress"><i data-progress="${m.coverage}"></i></div><small class="muted">${m.attempts} risposte · ${m.wrong} errori${m.attempts?' • '+m.accuracy+'% precisione':''}</small></div><b>${m.attempts?m.coverage+'% studiate':'—'}</b></div>`}).join('')}`}
function review(){return `<h1>Ripasso • ${course().name}</h1>${card('◎','Ripasso intelligente','Sessione adattiva su debolezze e recenza','startAdaptive')}${card('◆','Livello di difficoltà','Scegli il livello 1, 2 o 3','difficultyScreen')}${card('◉','Domande mai viste',`${activeQuestions().filter(q=>!(S.stats[q.id]?.attempts>0)).length} domande`,'startUnseen')}${card('↘','Aree deboli','Domande con rendimento più basso','startWeak')}${card('⚠','Errori da ripassare',`${reviewItems().length} domande`,'showErrors')}${card('★','Preferiti',`${S.favorites.size} domande`,'showFavorites')}`}
function render(){setTabs();let v=$('#view');if(S.session)return renderSession();v.innerHTML=({home:home,study,quiz:quick,stats,review}[S.tab]||home)();applyDynamicUI()}
function reviewSnapshot(q){return {id:q.id,module:q.module,moduleName:q.moduleName,chapter:q.chapter||'',subtopic:q.subtopic||'',level:q.level||1,difficulty:q.difficulty||1,question:q.question,answers:[...(q.answers||[])],correct:q.correct,explanation:q.explanation||'',sourceBasis:q.sourceBasis||'',sourceRefs:q.sourceRefs||[],media:q.media||[],sourceType:q.sourceType||'uploaded_material',chapterId:q.chapterId,topicId:q.topicId,conceptId:q.conceptId||conceptKey(q),dynamic:!!q.dynamic}}
function spacedInterval(streak){return [0,1,3,7,14,30,60][Math.min(6,Math.max(0,streak))]||1}
function record(q,sel,elapsed=0){let ok=sel===q.correct,x=S.stats[q.id]||{attempts:0,correct:0,wrong:0,totalTime:0,recoveryStreak:0,srStreak:0};x.attempts++;x.lastSeen=Date.now();x.totalTime=(x.totalTime||0)+Math.max(0,elapsed);x.lastAnswer=sel;x.module=String(q.module);x.conceptKey=conceptKey(q);x.dynamic=!!q.dynamic;if(ok){x.correct++;x.srStreak=(x.srStreak||0)+1;x.intervalDays=spacedInterval(x.srStreak);x.dueAt=Date.now()+x.intervalDays*86400000;if(S.mistakes.has(q.id)){x.recoveryStreak=(x.recoveryStreak||0)+1;if(x.recoveryStreak>=2){S.mistakes.delete(q.id);delete S.mistakeBank[q.id];x.recoveryStreak=0}}}else{x.wrong++;x.srStreak=0;x.intervalDays=0;x.dueAt=Date.now();x.recoveryStreak=0;S.mistakes.add(q.id);S.mistakeBank[q.id]=reviewSnapshot(q)}x.mastery=Math.round(((x.correct||0)/(x.attempts||1))*100);S.stats[q.id]=x;save();return ok}
function spacedDuePool(n=20){let now=Date.now(),allowed=new Set(activeMods().map(String)),bank=new Map(activeQuestions().map(q=>[q.id,q]));Object.entries(S.mistakeBank).forEach(([id,q])=>{if(q&&allowed.has(String(q.module)))bank.set(id,q)});let due=[];for(const [id,q] of bank){let x=S.stats[id];if(x?.attempts>0&&((x.dueAt||0)<=now))due.push(q)}due.sort((a,b)=>(S.stats[a.id]?.dueAt||0)-(S.stats[b.id]?.dueAt||0));return uniqueConcepts(due).slice(0,n)}
function continueStudy(){let n=SETTINGS.length,due=spacedDuePool(n),used=new Set(due.map(conceptKey)),unseen=unseenPool(n).filter(q=>!used.has(conceptKey(q))),items=[...due,...unseen].slice(0,n);items.forEach(q=>used.add(conceptKey(q)));if(items.length<n){let weak=weakPool(n*2).filter(q=>!used.has(conceptKey(q)));items.push(...weak.slice(0,n-items.length))}if(items.length<n){let extra=adaptivePool(n*2).filter(q=>!new Set(items.map(conceptKey)).has(conceptKey(q)));items.push(...extra.slice(0,n-items.length))}if(!items.length)items=buildDynamicQuiz(n);start(items.slice(0,n),'Continua studio intelligente',false)}
function startModule(n){start(S.questions.filter(q=>q.module==n),`Materia ${n} – ${MODS[n]}`,false)}
function startQuiz(){start(shuffle(uniqueConcepts(activeQuestions())).slice(0,SETTINGS.length),'Quiz rapido',false)}
function difficultyScreen(){S.session=null;let aq=activeQuestions();let count=l=>aq.filter(q=>Number(q.difficulty||1)===l).length;$('#view').innerHTML=`<button class="back" data-action="go-review">‹ Indietro</button><h1>Difficoltà • ${course().name}</h1><div class="selectorIntro">Scegli la difficoltà delle domande di allenamento.</div>${card('◇','Difficoltà 1 · Base',`${count(1)} domande`,'difficulty1')}${card('◆','Difficoltà 2 · Applicazione',`${count(2)} domande`,'difficulty2')}${card('⬢','Difficoltà 3 · Approfondimento',`${count(3)} domande`,'difficulty3')}${card('◎','Difficoltà mista',`${aq.length} domande di tutti i livelli`,'difficultyMixed')}`}
function startDifficulty(level=null){let pool=activeQuestions().filter(q=>level==null||Number(q.difficulty||1)===Number(level));let x=shuffle(uniqueConcepts(pool)).slice(0,SETTINGS.length);if(!x.length)return listQuestions(level==null?'Difficoltà mista':`Difficoltà ${level}`,[]);start(x,level==null?'Difficoltà mista':`Difficoltà ${level}`,false)}
function startDifficult(){startDifficulty(3)}
function startAdaptive(){let due=spacedDuePool(SETTINGS.length),used=new Set(due.map(conceptKey)),adaptive=adaptivePool(SETTINGS.length*2).filter(q=>!used.has(conceptKey(q))),x=[...due,...adaptive].slice(0,SETTINGS.length);if(!x.length)x=shuffle(uniqueConcepts(activeQuestions())).slice(0,SETTINGS.length);start(x,'Ripasso intelligente · ripetizione dilazionata',false)}
function startUnseen(){let x=unseenPool(SETTINGS.length);if(!x.length)return listQuestions('Domande mai viste',[]);start(x,'Domande mai viste',false)}
function startWeak(){let x=weakPool(SETTINGS.length);if(!x.length)return listQuestions('Aree deboli',[]);start(x,'Aree deboli',false)}
function start(items,title,exam){S.session={items:randomizeSession(items,title),title,exam,index:0,selected:null,checked:false,answers:[],seconds:SETTINGS.timer,timer:null,finished:false,questionStarted:Date.now()};renderSession();if(exam)tick()}
function renderSession(){let s=S.session,v=$('#view');if(!s)return render();if(s.finished||s.index>=s.items.length){return result()}let q=s.items[s.index],pct=s.index/Math.max(1,s.items.length)*100;v.innerHTML=`<button class="back" data-action="stopSession">‹ Indietro</button><div class="qtop"><span>Materia ${q.module} • ${esc(q.chapter)}</span><span>${s.index+1}/${s.items.length}</span></div><div class="progress"><i data-progress="${pct}"></i></div>${s.exam?`<div class="timer ${s.seconds<=15?'red':''}"><b>◷ ${s.seconds}s</b><div class="progress grow"><i data-progress="${s.seconds/SETTINGS.timer*100}"></i></div></div>`:''}<div class="chips"><span class="chip">${esc(MODS[q.module])}</span><span class="chip">Difficoltà ${q.difficulty}</span>${q.sourceType==='official_web'?'<span class="chip">Approfondimento online</span>':''}</div><div class="question">${esc(q.question)}</div>${questionMedia(q)}${q.answers.map((a,i)=>answerHtml(q,i,a)).join('')}${s.checked&&!s.exam?`<div class="feedback ${s.selected===q.correct?'ok':'no'}"><b>${s.selected===q.correct?'Risposta corretta':'Risposta errata'}</b><div>${esc(q.explanation)}</div><small>${esc(q.sourceBasis||'')}</small>${q.sourceRefs?.length?`<a class="sourceLink" href="${esc(sourceURL(q.sourceRefs[0])||'#')}" target="_blank" rel="noopener">Apri fonte</a>`:''}</div>`:''}<div class="actions"><button class="btn" data-action="toggleFav" data-id="${esc(q.id)}">${S.favorites.has(q.id)?'★ Preferita':'☆ Salva'}</button><button class="btn primary" ${s.selected==null&&!s.checked?'disabled':''} data-action="advance">${s.exam?'Conferma':s.checked?'Successiva':'Conferma'}</button></div>`;applyDynamicUI()}
function answerHtml(q,i,a){let s=S.session,cls='';if(s.selected===i)cls=' selected';if(s.checked&&!s.exam){if(i===q.correct)cls=' correct';else if(i===s.selected)cls=' wrong'}return `<button class="answer${cls}" data-action="selectAnswer" data-index="${i}"><span class="letter">${['A','B','C','D'][i]||i+1}</span><span>${esc(a)}</span></button>`}
function selectAnswer(i){let s=S.session;if(!s||s.checked)return;s.selected=i;if(!s.exam){s.checked=true;record(s.items[s.index],i,Math.round((Date.now()-s.questionStarted)/1000))}renderSession()}
function advance(timed=false){let s=S.session,q=s.items[s.index];if(s.exam){let sel=timed?null:s.selected;if(sel==null&&!timed)return;let ok=record(q,sel,Math.round((Date.now()-s.questionStarted)/1000));s.answers.push({q,selected:sel,ok})}else if(s.checked){s.answers.push({q,selected:s.selected,ok:s.selected===q.correct})}else return;clearInterval(s.timer);s.timer=null;s.selected=null;s.checked=false;if(s.index+1>=s.items.length){s.finished=true;result()}else{s.index++;s.seconds=SETTINGS.timer;s.questionStarted=Date.now();renderSession();if(s.exam)tick()}}
function tick(){let s=S.session;clearInterval(s.timer);s.timer=setInterval(()=>{if(!S.session||S.session!==s){clearInterval(s.timer);return}s.seconds--;if(s.seconds<=0){clearInterval(s.timer);advance(true)}else renderSession()},1000)}
function stopSession(){if(S.session?.timer)clearInterval(S.session.timer);S.session=null;render()}
function result(){let s=S.session,a=s.answers,c=a.filter(x=>x.ok).length,p=a.length?Math.round(c/a.length*100):0,pass=p>=SETTINGS.passMark;let mods=[...new Set(a.map(x=>x.q.module))].sort((x,y)=>x-y);$('#view').innerHTML=`<button class="back" data-action="stopSession">‹ Home</button><div class="score"><div class="scoreIcon">${pass?'✓':'✕'}</div><h2>${s.exam?(pass?'Soglia raggiunta':'Soglia non raggiunta'):'Quiz completato'}</h2><div class="pct ${s.exam?(pass?'pass':'fail'):''}">${p}%</div><div class="muted">${c} corrette su ${a.length} • soglia di allenamento ${SETTINGS.passMark}%</div></div>${mods.map(m=>{let x=a.filter(z=>z.q.module===m),cc=x.filter(z=>z.ok).length,pp=x.length?Math.round(cc/x.length*100):0;return `<div class="module"><b>Materia ${m}</b><span>${cc}/${x.length}</span><span class="grow"></span><b>${pp}%</b></div>`}).join('')}${a.some(x=>!x.ok)?`<button class="btn primary" data-action="sessionErrors">Rivedi gli errori</button>`:''}`;applyDynamicUI()}
function sessionErrors(){let bad=S.session.answers.filter(x=>!x.ok);listQuestions('Errori sessione',bad.map(x=>x.q),true)}
function toggleFav(id){let q=S.session?.items?.find(x=>x.id===id)||S.questions.find(x=>x.id===id)||S.favoriteBank[id];if(S.favorites.has(id)){S.favorites.delete(id);delete S.favoriteBank[id]}else{S.favorites.add(id);if(q)S.favoriteBank[id]=reviewSnapshot(q)}save();renderSession()}
function reviewItems(){let out=[];for(const id of S.mistakes){let q=S.mistakeBank[id]||S.questions.find(x=>x.id===id);if(q)out.push(q)}return uniqueConcepts(out)}
function syncReviewStore(){let changed=false;for(const id of [...S.mistakes]){if(!S.mistakeBank[id]){let q=S.questions.find(x=>x.id===id);if(q){S.mistakeBank[id]=reviewSnapshot(q);changed=true}}}if(changed)save()}
function showErrors(){syncReviewStore();let x=reviewItems();if(!x.length)return listQuestions('Errori da ripassare',[]);start(x,'Errori da ripassare · 2 risposte corrette per recuperarli',false)}
function showFavorites(){let allowed=new Set(activeMods().map(String)),x=[];for(const id of S.favorites){let q=S.favoriteBank[id]||S.questions.find(z=>z.id===id);if(q&&allowed.has(String(q.module)))x.push(q)}x=uniqueConcepts(x);if(!x.length)return listQuestions('Preferiti',[]);start(x,'Preferiti',false)}
function listQuestions(title,items,showCorrect=false){S.session=null;$('#view').innerHTML=`<button class="back" data-action="go-review">‹ Indietro</button><h1>${title}</h1>${items.length?items.map(q=>`<div class="card" data-action="reviewOne" data-id="${esc(q.id)}"><div class="grow"><strong>${esc(q.question)}</strong><small>Materia ${q.module} • ${esc(q.chapter)}</small>${showCorrect?`<div class="correctText">Corretta: ${esc(q.answers[q.correct])}</div><div class="muted">${esc(q.explanation)}</div>`:''}</div><b>›</b></div>`).join(''):`<div class="empty">Nessuna domanda presente.</div>`}`}
let EXAM_SETUP=null;
function examSetup(){S.session=null;EXAM_SETUP={count:Math.min(SETTINGS.length,activeQuestions().length),timer:SETTINGS.timer,pass:SETTINGS.passMark};drawExamSetup()}
function drawExamSetup(){let {count,timer,pass}=EXAM_SETUP;$('#view').innerHTML=`<button class="back" data-action="go-home">‹ Indietro</button><h1>Simulazione di allenamento</h1><div class="score"><div class="scoreIcon">◷</div><h2>${course().name} – ${course().desc}</h2></div><div class="stepper"><span>Numero di domande</span><div><button data-action="exam-count" data-delta="-10">−</button> <b>${count}</b> <button data-action="exam-count" data-delta="10">+</button></div></div><div class="stepper"><span>Tempo per domanda</span><div><button data-action="exam-time" data-delta="-15">−</button> <b>${timer}s</b> <button data-action="exam-time" data-delta="15">+</button></div></div><div class="stepper"><span>Soglia di allenamento</span><div><button data-action="exam-pass" data-delta="-5">−</button> <b>${pass}%</b> <button data-action="exam-pass" data-delta="5">+</button></div></div><button class="btn primary fullWidth" data-action="exam-start">Avvia simulazione</button>`}

function settingsScreen(){S.session=null;$('#view').innerHTML=`<button class="back" data-action="go-home">‹ Home</button><h1>Impostazioni</h1><div class="setting"><div><b>Timer simulazione</b><small>Secondi per domanda</small></div><select data-change="timer">${[30,45,60,75,90,105,120,150,180].map(x=>`<option value="${x}" ${SETTINGS.timer==x?'selected':''}>${x}s</option>`).join('')}</select></div><div class="setting"><div><b>Soglia di allenamento</b><small>Personalizzabile, non ufficiale</small></div><select data-change="passMark">${[50,55,60,65,70,75,80,85,90,95,100].map(x=>`<option value="${x}" ${SETTINGS.passMark==x?'selected':''}>${x}%</option>`).join('')}</select></div><div class="setting"><div><b>Lunghezza quiz</b><small>Domande per sessione</small></div><select data-change="length">${[10,20,30,40,50,75,100].map(x=>`<option value="${x}" ${SETTINGS.length==x?'selected':''}>${x}</option>`).join('')}</select></div><button class="btn danger" data-action="resetProgress">Azzera progressi, errori e preferiti</button><div class="disclaimer">Quiz Carabinieri v3.2. Le impostazioni della simulazione sono parametri di allenamento. I progressi vengono salvati su questo browser.</div>`}
function setPassMark(v){SETTINGS.passMark=Number(v);save();settingsScreen()}
function setTimer(v){SETTINGS.timer=Number(v);save()}function setLength(v){SETTINGS.length=Number(v);save()}
function resetProgress(){if(confirm('Azzera statistiche, errori e preferiti?')){S.stats={};S.mistakes.clear();S.mistakeBank={};S.favorites.clear();S.favoriteBank={};save();settingsScreen()}}
function applyDynamicUI(){document.querySelectorAll('[data-progress]').forEach(el=>{let n=Math.max(0,Math.min(100,Number(el.dataset.progress)||0));el.style.width=n+'%'})}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;const actions={
'go-study':()=>go('study'),'go-review':()=>go('review'),'go-home':()=>go('home'),difficultyScreen,difficulty1:()=>startDifficulty(1),difficulty2:()=>startDifficulty(2),difficulty3:()=>startDifficulty(3),difficultyMixed:()=>startDifficulty(null),settingsScreen,startQuiz,startAdaptive,continueStudy,installApp,closeInstallHelp,startDifficult,startUnseen,startWeak,showErrors,showFavorites,examSetup,stopSession,advance,sessionErrors,resetProgress,
subjectScreen:()=>subjectScreen(el.dataset.module),subjectsView,startChapter:()=>startChapter(el.dataset.chapter),startChapterRandom:()=>startChapterRandom(el.dataset.chapter),startModuleRandom:()=>startModuleRandom(el.dataset.module),startModule:()=>startModule(el.dataset.module),selectAnswer:()=>selectAnswer(Number(el.dataset.index)),toggleFav:()=>toggleFav(el.dataset.id),reviewOne:()=>{let q=S.mistakeBank[el.dataset.id]||S.favoriteBank[el.dataset.id]||S.questions.find(x=>x.id===el.dataset.id);if(q)start([q],'Ripasso',false)},
'exam-count':()=>{EXAM_SETUP.count=Math.max(10,Math.min(activeQuestions().length,EXAM_SETUP.count+Number(el.dataset.delta)));drawExamSetup()},
'exam-time':()=>{EXAM_SETUP.timer=Math.max(30,Math.min(180,EXAM_SETUP.timer+Number(el.dataset.delta)));drawExamSetup()},
'exam-pass':()=>{EXAM_SETUP.pass=Math.max(50,Math.min(100,EXAM_SETUP.pass+Number(el.dataset.delta)));drawExamSetup()},
'exam-start':()=>{SETTINGS.timer=EXAM_SETUP.timer;SETTINGS.passMark=EXAM_SETUP.pass;SETTINGS.length=EXAM_SETUP.count;save();start(buildDynamicQuiz(EXAM_SETUP.count),'Simulazione di allenamento',true)}
};if(actions[a])actions[a]()});
document.addEventListener('change',e=>{let k=e.target.dataset.change;if(k==='timer')setTimer(e.target.value);else if(k==='passMark')setPassMark(e.target.value);else if(k==='length')setLength(e.target.value)});
document.querySelectorAll('#tabs button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.tab)));
Promise.all(['questions.json','catalog.json'].map(url=>fetch(url).then(r=>{if(!r.ok)throw new Error(url);return r.json()}))).then(([q,catalog])=>{S.catalog=catalog;S.questions=(Array.isArray(q)?q:[]).map(normalize).filter(validQuestion);if(localStorage.getItem(profileKey('bankVersion'))!==catalog.bankVersion){for(const id of (['2.0.0','3.0.0','3.1.0','3.2.0'].includes(localStorage.getItem(profileKey('bankVersion')))?[]:catalog.correctedLegacyIds)){delete S.stats[id];S.mistakes.delete(id);delete S.mistakeBank[id];if(S.favorites.has(id)){const current=S.questions.find(x=>x.id===id);if(current)S.favoriteBank[id]=reviewSnapshot(current)}}save();localStorage.setItem(profileKey('bankVersion'),catalog.bankVersion)}syncReviewStore();setTimeout(()=>{$('#splash').remove();$('#app').classList.remove('hidden');render()},1800)}).catch(e=>{$('#splash').innerHTML='<div class="loadError">Errore caricamento banca domande.</div>'});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));


function buildDynamicQuiz(count=SETTINGS.length,module=null){let pool=module==null?activeQuestions():activeQuestions().filter(q=>String(q.module)===String(module));return shuffle(uniqueConcepts(pool)).slice(0,count)}
startQuiz=function(){const title='Quiz rapido';start(pickSessionQuestions(activeQuestions(),SETTINGS.length,title),title,false)};
startModule=function(n){start(buildDynamicQuiz(activeQuestions().length,n),MODS[n],false)};

function sourceURL(ref){const src=S.catalog.sources.find(x=>x.id===ref.sourceId);return src?sourceDocumentURL(src.readableFile||src.file,!src.readableFile&&ref.kind==='pdfPage'?ref.start:null):null}
function subjectView(n){let subject=S.catalog.subjects.find(x=>x.module==n),chapters=S.catalog.chapters.filter(c=>c.subjectId===subject.id),sources=subject.sourceIds.map(id=>S.catalog.sources.find(x=>x.id===id));return `<button class="back" data-action="subjectsView">‹ Tutte le materie</button><h1>${esc(subject.name)}</h1><div class="selectorIntro">${subject.questionCount} domande · ${chapters.length} capitoli didattici. ${n==1?'213 nuovi quesiti dalla sinossi, figure originali e approfondimenti online identificati.':'Le dispense sono consultabili sotto.'} Domande e risposte vengono mescolate a ogni sessione. La banca non copre ancora ogni sezione dei testi.</div><button class="btn primary fullWidth" data-action="startModule" data-module="${n}">Quiz completo della materia</button><button class="btn fullWidth" data-action="startModuleRandom" data-module="${n}">Sessione casuale · ${Math.min(SETTINGS.length,subject.questionCount)} domande</button><h2>Scegli un capitolo</h2><input class="bankSearch" data-filter="bank" type="search" placeholder="Cerca un capitolo…" aria-label="Cerca un capitolo">${chapters.map(c=>`<div class="chapterRow bankItem" data-search="${esc(c.name.toLocaleLowerCase('it'))}"><button class="module chapterFull" data-action="startChapter" data-chapter="${esc(c.id)}"><div class="grow"><b>${esc(c.name)}</b><small>${c.questionCount} ${c.questionCount===1?'domanda':'domande'} · quiz completo</small></div><b>›</b></button><button class="chapterRandom" data-action="startChapterRandom" data-chapter="${esc(c.id)}">Casuale · ${Math.min(SETTINGS.length,c.questionCount)} ${Math.min(SETTINGS.length,c.questionCount)===1?'domanda':'domande'}</button></div>`).join('')}<h2>${n==1?'Dispense e approfondimenti ufficiali':'Dispense della materia'}</h2>${sources.map(src=>`<a class="sourceCard" href="${esc(sourceDocumentURL(src.file))}" target="_blank" rel="noopener"><b>${esc(src.title)}</b><small>${src.format==='pdf'?src.unitCount+' pagine PDF':src.format==='html'?'Approfondimento ufficiale online':'Documento Word'}${src.contentEditionNote?' · '+esc(src.contentEditionNote):''}</small></a>${src.supplementFile?`<a class="sourceCard" href="dispense/${esc(src.supplementFile)}" target="_blank" rel="noopener"><b>Testo incollato in chat</b><small>Trascrizione di supporto alla sinossi</small></a>`:''}${src.readableFile?`<a class="sourceCard" href="dispense/${esc(src.readableFile)}" target="_blank" rel="noopener"><b>Testo completo recuperato</b><small>Include le righe conservate fuori dal bordo del PDF</small></a>`:''}`).join('')}`}
function subjectScreen(n){S.studyModule=Number(n);go('study')}
function subjectsView(){S.studyModule=null;go('study')}
function startChapter(id){const chapter=S.catalog.chapters.find(x=>x.id===id);if(!chapter)return;const items=shuffle(activeQuestions().filter(q=>q.chapterId===id));start(items,chapter.name,false)}
document.addEventListener('input',e=>{if(e.target.dataset.filter!=='bank')return;const query=e.target.value.toLocaleLowerCase('it').normalize('NFD').replace(/[\u0300-\u036f]/g,'');document.querySelectorAll('.bankItem').forEach(el=>{el.hidden=!el.dataset.search.normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(query)})});

function sessionHistory(){try{return JSON.parse(localStorage.getItem(profileKey('sessionHistory'))||'{}')}catch{return {}}}
function pickSessionQuestions(pool,count,key){const unique=uniqueConcepts(pool),last=sessionHistory()[key],previous=new Set(last?.order||[]);return [...shuffle(unique.filter(q=>!previous.has(q.id))),...shuffle(unique.filter(q=>previous.has(q.id)))].slice(0,Math.min(count,unique.length))}
function randomizeSession(items,key){const history=sessionHistory(),last=history[key]||{},options={};let pool=shuffle(uniqueConcepts(items));if(pool.length>1&&JSON.stringify(pool.map(q=>q.id))===JSON.stringify(last.order))pool=[...pool.slice(1),pool[0]];const result=pool.map(q=>{const base=S.questions.find(x=>x.id===q.id)||q;let permutation=shuffle(base.answers.map((_,i)=>i));if(JSON.stringify(permutation)===JSON.stringify(last.options?.[q.id]))permutation=[...permutation.slice(1),permutation[0]];options[q.id]=permutation;return {...base,answers:permutation.map(i=>base.answers[i]),correct:permutation.indexOf(base.correct),optionOrder:permutation}});history[key]={order:result.map(q=>q.id),options};try{localStorage.setItem(profileKey('sessionHistory'),JSON.stringify(history))}catch{}return result}
function startModuleRandom(n){const title='Sessione casuale · '+MODS[n];start(pickSessionQuestions(activeQuestions().filter(q=>q.module==n),SETTINGS.length,title),title,false)}
function startChapterRandom(id){const chapter=S.catalog.chapters.find(c=>c.id===id);if(!chapter)return;const title='Casuale · '+chapter.name;start(pickSessionQuestions(activeQuestions().filter(q=>q.chapterId===id),SETTINGS.length,title),title,false)}
function questionMedia(q){return (q.media||[]).map(m=>`<figure class="questionFigure"><a href="${esc(m.file)}" target="_blank" rel="noopener" aria-label="Apri immagine ingrandita"><img src="${esc(m.file)}" alt="${esc(m.alt)}" loading="eager"></a><figcaption>${esc(m.caption)} · Tocca per ingrandire</figcaption></figure>`).join('')}

function sourceDocumentURL(file,page){const split=['centrale-operativa.pdf','informatica-arma.docx','storia-arma.docx'].includes(file);return split?'source.html?file='+encodeURIComponent(file)+(page?'&page='+encodeURIComponent(page):''):'dispense/'+file+(page?'#page='+encodeURIComponent(page):'')}
